name: Push

on:
  push:
    branches:
    - master
  pull_request:


jobs:
  spec:
    name: OpenAPI in JS
    if: "!contains(github.event.head_commit.message, 'Bump version') || github.event_name != 'push'"
    runs-on: ubuntu-20.04
    steps:
    - name: actions/checkout
      uses: actions/checkout@v2
    - name: openapitools/openapi-generator-cli
      run: |
        make -C tests spec
  lint-enforce:
    name: openapi-enforcer
    if: "!contains(github.event.head_commit.message, 'Bump version') || github.event_name != 'push'"
    runs-on: ubuntu-20.04
    steps:
    - name: actions/checkout
      uses: actions/checkout@v2
    - name: path
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: install
      run: |
        pip3 install jinja2-cli
    - name: openapi-enforcer-cli
      run: |
        make -C tests lint-enforce
  lint-ibm:
    name: ibm-openapi-validator
    if: "!contains(github.event.head_commit.message, 'Bump version') || github.event_name != 'push'"
    runs-on: ubuntu-20.04
    steps:
    - name: actions/checkout
      uses: actions/checkout@v2
    - name: path
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: install
      run: |
        pip3 install jinja2-cli
    - name: lint-openapi
      run: |
        make -C tests lint-ibm
  no-confusion:
    name: No confusion
    if: "!contains(github.event.head_commit.message, 'Bump version') || github.event_name != 'push'"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - uses: athenianco/no-confusion-action@1.1.1
      with:
        include: '["**/*.yaml", "**/*.yml"]'
        exclude_patterns: '{"openapi.yaml": ["Sub-tásks"], ".github/workflows/push.yml": ["Sub-tásks"]}'
  bump_version:
    name: Bump the version
    needs: [spec, no-confusion]
    if: "!contains(github.event.head_commit.message, 'Bump version') && github.ref == 'refs/heads/master' && github.event_name == 'push'"
    runs-on: ubuntu-20.04
    steps:
    - name: actions/checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 100
        persist-credentials: false
    - name: current_version
      run: |
        set -x
        echo "current_version=$(grep '  version: ' openapi.yaml | cut -d: -f2 | sed 's/ //g')" >> $GITHUB_ENV
    - name: FragileTech/bump-version
      uses: FragileTech/bump-version@main
      with:
        current_version: "${{ env.current_version }}"
        files: openapi.yaml
        commit_name: Groundskeeper Willie
        commit_email: bot@athenian.co
        login: gkwillie
        token: ${{ secrets.GKWILLIE_TOKEN }}

